const DATA = [
	{
		id: 1,
		user: "Perna Longa",
		title: "Grama Alta",
		type: 'green',
		distance: 17,
		location: "Jardins - Sao Paulo",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photourl: "https://static.wikia.nocookie.net/looneytunes/images/b/ba/BD1DC604-0990-445E-A75E-3E2CB91741EF.png/revision/latest/top-crop/width/360/height/360?cb=20201206015718",
		requirements: [
			"Disponibilidade de Tarde",
			"Ter conhecimento no manuseio de ferramentas de casa",
			"Concluir em 1 dia",
		],
	},
	{
		id: 2,
		user: "Patolino",
		title: "Encanamento Vazando",
		type: 'blue',
		distance: 25,
		location: "Jurunas - Belem",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photourl: "https://i.pinimg.com/originals/f1/c3/bb/f1c3bbe46d59f01b71ff3e2d8a7fecab.jpg",
		requirements: [
			"Req 1",
			"Req 2",
			"Req 3",
		],
	},
	{
		id: 3,
		user: "Ligeirinho",
		title: "Problemas no Telhado",
		type: 'red',
		distance: 6,
		location: "Jurunas - Belem",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photourl: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fe/Speedy_Gonzales.svg/1200px-Speedy_Gonzales.svg.png",
		requirements: [
			"Req 1",
			"Req 2",
			"Req 3",
		],
	},
	{
		id: 4,
		user: "Papa-Léguas",
		title: "Fazer App",
		type: 'yellow',
		distance: 100,
		location: "Curitiba",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photourl: "https://i.pinimg.com/originals/78/89/ed/7889edbd6fdcf4e63f13efc538c78dbc.jpg",
		requirements: [
			"Req 1",
			"Req 2",
			"Req 3",
			"Req 4",
		],
	},
	{
		id: 5,
		user: "Frajola",
		title: "Fazer App",
		type: 'yellow',
		distance: 100,
		location: "Curitiba",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photourl: "https://i.pinimg.com/474x/a1/47/c0/a147c01b872bb34cc506fb3f50ae5165.jpg",
		requirements: [
			"Req 1",
			"Req 2",
			"Req 3",
			"Req 4",
		],
	},
	{
		id: 6,
		user: "Marvin, o Marciano",
		title: "Fazer App",
		type: 'yellow',
		distance: 100,
		location: "Curitiba",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photourl: "https://static.wikia.nocookie.net/dublagempedia/images/a/aa/Marvin_the_Martian.svg.png/revision/latest?cb=20171129225846&path-prefix=pt-br",
		requirements: [
			"Req 1",
			"Req 2",
			"Req 3",
			"Req 4",
		],
	},
];

export default DATA;
