const DATA = [
	{
		id: 1,
		user: "Kratos",
		title: "Grama Alta",
		type: 'green',
		distance: 17,
		location: "Jurunas - Belem",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photourl: "https://cdn.dribbble.com/users/458522/screenshots/4568564/kratos_1.jpg?compress=1&resize=300x300",
		requirements: [
			"Disponibilidade de Tarde",
			"Ter conhecimento no manuseio de ferramentas de casa",
			"Concluir em 1 dia",
		],
	},
	{
		id: 2,
		user: "Patolino",
		title: "Encanamento Vazando",
		type: 'blue',
		distance: 25,
		location: "Jurunas - Belem",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photourl: "https://i.pinimg.com/originals/f1/c3/bb/f1c3bbe46d59f01b71ff3e2d8a7fecab.jpg",
		requirements: [
			"Req 1",
			"Req 2",
			"Req 3",
		],
	},
	{
		id: 3,
		user: "Bruno Pinho",
		title: "Problemas no Telhado",
		type: 'red',
		distance: 6,
		location: "Jurunas - Belem",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photourl: "https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg",
		requirements: [
			"Req 1",
			"Req 2",
			"Req 3",
		],
	},
	{
		id: 4,
		user: "Wesley ",
		title: "Fazer App",
		type: 'yellow',
		distance: 100,
		location: "Curitiba",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photourl: "https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg",
		requirements: [
			"Req 1",
			"Req 2",
			"Req 3",
			"Req 4",
		],
	},
	{
		id: 5,
		user: "Wesley ",
		title: "Fazer App",
		type: 'yellow',
		distance: 100,
		location: "Curitiba",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photourl: "https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg",
		requirements: [
			"Req 1",
			"Req 2",
			"Req 3",
			"Req 4",
		],
	},
	{
		id: 6,
		user: "Wesley ",
		title: "Fazer App",
		type: 'yellow',
		distance: 100,
		location: "Curitiba",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photourl: "https://t3.ftcdn.net/jpg/03/46/83/96/360_F_346839683_6nAPzbhpSkIpb8pmAwufkC7c5eD7wYws.jpg",
		requirements: [
			"Req 1",
			"Req 2",
			"Req 3",
			"Req 4",
		],
	},
];

export default DATA;
